language: python
cache: pip
matrix:
  include:
  - python: "2.7"
  - python: "3.5"
  - python: "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install pytest-cov

script:
  - travis_wait 999 pytest --verbose --cov=.

after_success:
- codecov

